name: Build and release

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

permissions:
  # fix github release 403 error
  # https://github.com/softprops/action-gh-release/issues/236
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release --locked
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/libruzy.so
